### ISSUE TITLE
 GitHub Actionでの実行対応のリクエスト

### ISSUE THREAD

**Issue by koriym** [smeghead/php-class-diagram#63]
こんにちは。

私は、このプロジェクトに興味を持っているのですが、現状ではGitHub Actionでの実行がサポートされていないため、私のワークフローに組み込むことが難しい状況です。
プロジェクトをより多くのユーザーに利用してもらうために、GitHub Actionでの実行に対応してはいかがでしょうか。
これにより、CIパイプラインへの組み込みが容易になり、プロジェクトの利便性と可用性が向上すると考えています。

実現に向けて、以下のような対応を提案させていただきます。

* GitHub Actionのワークフロー設定ファイル（.github/workflows/php-class-diagram.yml）をプロジェクトに追加する。
* ワークフロー内でプロジェクトの実行に必要な手順を定義する（例：依存関係のインストール、ビルド、画像の生成の実行など）。
* リポジトリにサンプルのワークフロー設定ファイルを追加し、ユーザーが参考にできるようにする。

ご検討いただければ幸いです。
このプロジェクトを使用する機会を楽しみにしています。
ご不明な点やご提案などございましたら、お気軽にコメントください。
どうぞよろしくお願いいたします。

**Comment by koriym** [comment]
これは私たちのチームが作成した、ダイアグラム図を描画するGH actionです。もし参考になりましたら！
https://github.com/alps-asd/asd-action

**Comment by smeghead** [comment]
ご提案ありがとうございます。GitHub Action実行のサポートの提供は是非実現したいと思いました。
現状、私にGitHub Actionを軽く利用する程度の知識しかないため、GitHub Action実行のサポートに向けて調査をしてみます。
参考のGH action もありがとうございます。

**Comment by koriym** [comment]
@smeghead GH actionやprojectの作り方で分からないことがあれば私たちに聞いてください、協力いたします！
https://github.com/orgs/alps-asd/people

**Comment by smeghead** [comment]
@koriym @NaokiTsuchiya
ありがとうございます。
プロトタイプ的に、GH actionを作成しました。
https://github.com/smeghead/php-class-diagram-gh-action

上記のactionを使う例のプロジェクトです。クラス図がArtifactsにアップロードされることを確認しました。
https://github.com/smeghead/php-class-diagram-gh-action-example/actions/runs/9255989435

問題点や改善点などありましたらコメント頂けると嬉しいです。

**Comment by koriym** [comment]
生成だけでdeployがないでしょうか。
[peaceiris/actions-gh-page](https://github.com/peaceiris/actions-gh-pages)などで生成したアーティファクトをdeployします。

**Comment by koriym** [comment]
https://github.com/alps-asd/asd-action/blob/master/.github/workflows/asd.yml#L22-L27
こんな感じです。

**Comment by smeghead** [comment]
はい、このアクション(`smeghead/php-class-diagram-gh-action`)の役割を、ランナーの既定の作業ディレクトリ (GITHUB_WORKSPACE) に指定したファイル名でクラス図を配置するという部分までと位置付けました。
Github Pages にデプロイする場合は、`smeghead/php-class-diagram-gh-action`を利用するプロジェクト側で出力ファイル名はわかっているはずなので、ワークフローファイルの次のステップでGithub Pagesにデプロイするステップを記述してもらえれば対応可能と考えました。
Github Actionsのベストプラクティス的なところまでは把握できていない状態なので、上記の判断の自信はあまりないですが。

**Comment by koriym** [comment]
そうですね、こちらの勘違いです＞＜

**Comment by smeghead** [comment]
@koriym 
以下のGithub Actionsのアクションを提供するリポジトリのREADMEに説明や設定例等を記載しました。
[smeghead/php-class-diagram-gh-action](https://github.com/smeghead/php-class-diagram-gh-action)

php-class-diagramのREADMEからも、上のリポジトリへのリンクを追加しました。
問題等ありましたら、ご連絡ください。
