### ISSUE TITLE
Add `--hide-private` options.

### ISSUE THREAD

**Issue by smeghead** [smeghead/php-class-diagram#67]
#65 でプライベートメソッドを非表示にしたいという要望を頂きました。

クラスのプライベートメソッドとプライベートフィールドを非表示にする `--hide-private` というオプションの追加を考えています。
プライベートメソッドは非表示にして、プライベートフィールドは表示するという別々の制御をする必要があるのであれば、それぞれのオプションを追加する必要があります。

**Comment by smeghead** [comment]
@koriym 
v1.3.1 で、`--hide-private` オプションを実装しました。
`--hide-private-methods` を指定することで、private(protectedを含む)メソッドを出力しないよう制御できるようになりました。
dockerhubのイメージもv1.3.1に更新済ですので、Github Actionsでも利用可能と思います。

**Comment by koriym** [comment]
@smeghead 

Github Actionsでどのように指定するのでしょうか？

**Comment by smeghead** [comment]
@koriym 
https://github.com/smeghead/php-class-diagram-gh-action?tab=readme-ov-file#options
GitHub Actions php-class-diagram-gh-action で、`options` という入力パラメータがありますので、php-class-diagramに渡すオプションを指定可能です。

以下が使用例です。
https://github.com/smeghead/php-class-diagram/blob/3744569a9692e34feebaac617abe662e94d0b8c8/.github/workflows/php.yml#L64

**Comment by koriym** [comment]
@smeghead ありがとうございます！確認しました。素晴らしいですね！🎉

**Comment by smeghead** [comment]
@koriym 確認いただきありがとうございます、良かったです🤣
